EVENTS = [
 (9, "Germanic tribes destroy three Roman legions in the Teutoburg Forest.", "Battle of the Teutoburg Forest"),
 (14, "Augustus, the first Roman emperor, dies.", "Augustus"),
 (43, "The Roman conquest of Britain begins.", "Roman conquest of Britain"),
 (64, "The Great Fire of Rome burns for six days.", "Great Fire of Rome"),
 (70, "Roman forces destroy the Temple in Jerusalem.", "Siege of Jerusalem (70 CE)"),
 (79, "Vesuvius erupts, burying Pompeii and Herculaneum.", "Eruption of Mount Vesuvius in 79 AD"),
 (80, "The Colosseum opens in Rome.", "Colosseum"),
 (105, "Cai Lun presents papermaking to the Han court in China.", "Cai Lun"),
 (117, "The Roman Empire reaches its greatest extent under Trajan.", "Trajan"),
 (122, "Work begins on Hadrian's Wall across northern Britain.", "Hadrian's Wall"),
 (150, "Ptolemy compiles the Almagest, the standard astronomy for 1,400 years.", "Almagest"),
 (165, "The Antonine Plague sweeps the Roman Empire.", "Antonine Plague"),
 (193, "Rome sees five emperors claim the throne in a single year.", "Year of the Five Emperors"),
 (212, "Caracalla grants Roman citizenship to all free men of the empire.", "Constitutio Antoniniana"),
 (220, "The Han dynasty ends and China splits into the Three Kingdoms.", "Three Kingdoms"),
 (224, "The Sasanian Empire is founded in Persia.", "Sasanian Empire"),
 (235, "The Crisis of the Third Century begins in Rome.", "Crisis of the Third Century"),
 (260, "Persians capture the Roman emperor Valerian.", "Valerian (emperor)"),
 (271, "Work begins on the Aurelian Walls around Rome.", "Aurelian Walls"),
 (293, "Diocletian divides imperial rule among four emperors.", "Tetrarchy"),
 (320, "The Gupta Empire rises in northern India.", "Gupta Empire"),
 (330, "Constantine makes Constantinople the new capital of the empire.", "Constantinople"),
 (376, "Goths cross the Danube into the Roman Empire.", "Gothic War (376–382)"),
 (395, "The Roman Empire is divided for good into East and West.", "Theodosius I"),
 (410, "The Visigoths sack Rome.", "Sack of Rome (410)"),
 (451, "Attila's Huns are halted at the Catalaunian Plains.", "Battle of the Catalaunian Plains"),
 (455, "The Vandals sack Rome.", "Sack of Rome (455)"),
 (476, "The last Western Roman emperor is deposed.", "Fall of the Western Roman Empire"),
 (481, "Clovis becomes king of the Franks.", "Clovis I"),
 (493, "Theodoric the Great takes control of Italy.", "Theodoric the Great"),
 (529, "Justinian issues the first edition of his law code.", "Corpus Juris Civilis"),
 (541, "The Plague of Justinian strikes the Mediterranean world.", "Plague of Justinian"),
 (568, "The Lombards invade Italy.", "Lombards"),
 (581, "The Sui dynasty is founded and soon reunites China.", "Sui dynasty"),
 (604, "Prince Shotoku issues Japan's Seventeen-article constitution.", "Seventeen-article constitution"),
 (618, "The Tang dynasty is founded in China.", "Tang dynasty"),
 (622, "Muhammad's migration to Medina begins the Islamic calendar.", "Hijrah"),
 (636, "Arab armies defeat the Byzantines at the Yarmuk.", "Battle of the Yarmuk"),
 (645, "The Taika Reforms reshape the Japanese state.", "Taika Reform"),
 (661, "The Umayyad Caliphate is founded.", "Umayyad Caliphate"),
 (674, "Arab forces begin a long siege of Constantinople.", "Siege of Constantinople (674–678)"),
 (690, "Wu Zetian becomes China's only empress regnant.", "Wu Zetian"),
 (711, "Umayyad forces cross from Africa into Iberia.", "Umayyad conquest of Hispania"),
 (732, "Frankish forces defeat an Umayyad army near Tours.", "Battle of Tours"),
 (750, "The Abbasids overthrow the Umayyad Caliphate.", "Abbasid Revolution"),
 (762, "The Abbasid caliph al-Mansur founds Baghdad.", "Baghdad"),
 (793, "Vikings raid Lindisfarne, opening the Viking Age in Britain.", "Viking Age"),
 (794, "Heian-kyo, today's Kyoto, becomes Japan's capital.", "Heian-kyō"),
 (814, "Charlemagne dies at Aachen.", "Charlemagne"),
 (830, "The House of Wisdom flourishes in Baghdad.", "House of Wisdom"),
 (843, "The Treaty of Verdun divides Charlemagne's empire.", "Treaty of Verdun"),
 (862, "Rurik begins to rule at Novgorod.", "Rurik"),
 (868, "The Diamond Sutra, the oldest dated printed book, is made in China.", "Diamond Sutra"),
 (878, "Alfred the Great defeats the Danes at Edington.", "Battle of Edington"),
 (907, "The Tang dynasty collapses.", "Tang dynasty"),
 (911, "Rollo the Viking is granted the land that becomes Normandy.", "Treaty of Saint-Clair-sur-Epte"),
 (929, "Abd al-Rahman III proclaims the Caliphate of Cordoba.", "Caliphate of Córdoba"),
 (960, "The Song dynasty is founded in China.", "Song dynasty"),
 (969, "The Fatimids found Cairo.", "Cairo"),
 (1000, "Leif Erikson reaches North America.", "Leif Erikson"),
 (1008, "Murasaki Shikibu is writing The Tale of Genji.", "The Tale of Genji"),
 (1016, "Cnut the Great becomes king of England.", "Cnut"),
 (1044, "A Chinese military manual records a formula for gunpowder.", "Wujing Zongyao"),
 (1054, "Astronomers record a supernova that leaves the Crab Nebula.", "SN 1054"),
 (1066, "The Normans conquer England.", "Norman Conquest"),
 (1086, "William the Conqueror's Domesday Book surveys England.", "Domesday Book"),
 (1088, "The University of Bologna is founded.", "University of Bologna"),
 (1099, "Crusaders capture Jerusalem.", "Siege of Jerusalem (1099)"),
 (1150, "Angkor Wat is completed in the Khmer Empire.", "Angkor Wat"),
 (1187, "Saladin retakes Jerusalem.", "Siege of Jerusalem (1187)"),
 (1192, "Minamoto no Yoritomo becomes shogun of Japan.", "Kamakura shogunate"),
 (1206, "Genghis Khan is proclaimed ruler of the Mongols.", "Genghis Khan"),
 (1215, "King John seals Magna Carta.", "Magna Carta"),
 (1241, "Mongol armies defeat the Hungarians at Mohi.", "Battle of Mohi"),
 (1258, "The Mongols sack Baghdad.", "Siege of Baghdad (1258)"),
 (1271, "Marco Polo sets out for China.", "Marco Polo"),
 (1279, "Kublai Khan's Yuan dynasty completes the conquest of China.", "Yuan dynasty"),
 (1291, "The last crusader stronghold at Acre falls.", "Siege of Acre (1291)"),
 (1299, "Osman I founds what becomes the Ottoman state.", "Ottoman Empire"),
 (1321, "Dante completes the Divine Comedy.", "Divine Comedy"),
 (1325, "The Mexica found Tenochtitlan.", "Tenochtitlan"),
 (1337, "The Hundred Years' War begins.", "Hundred Years' War"),
 (1347, "The Black Death reaches Europe.", "Black Death"),
 (1368, "The Ming dynasty is founded in China.", "Ming dynasty"),
 (1381, "The Peasants' Revolt breaks out in England.", "Peasants' Revolt"),
 (1400, "Geoffrey Chaucer, author of The Canterbury Tales, dies.", "Geoffrey Chaucer"),
 (1405, "Zheng He sets out on the first of seven great voyages.", "Zheng He"),
 (1415, "The English defeat the French at Agincourt.", "Battle of Agincourt"),
 (1428, "The Aztec Triple Alliance is formed.", "Aztec Triple Alliance"),
 (1431, "Joan of Arc is burned at Rouen.", "Joan of Arc"),
 (1438, "Pachacuti begins building the Inca Empire.", "Pachacuti"),
 (1440, "Gutenberg develops printing with movable type.", "Printing press"),
 (1453, "The Ottomans capture Constantinople.", "Fall of Constantinople"),
 (1455, "The Wars of the Roses begin in England.", "Wars of the Roses"),
 (1492, "Columbus reaches the Caribbean.", "Voyages of Christopher Columbus"),
 (1498, "Vasco da Gama reaches India by sea.", "Vasco da Gama"),
 (1503, "Leonardo da Vinci begins the Mona Lisa.", "Mona Lisa"),
 (1519, "Magellan's expedition sets out to sail around the world.", "Magellan expedition"),
 (1521, "Tenochtitlan falls to Cortés and his allies.", "Fall of Tenochtitlan"),
 (1526, "Babur founds the Mughal Empire at Panipat.", "First Battle of Panipat"),
 (1543, "Copernicus publishes his model of a Sun-centred cosmos.", "De revolutionibus orbium coelestium"),
 (1556, "The Shaanxi earthquake, the deadliest on record, strikes China.", "1556 Shaanxi earthquake"),
 (1571, "The Holy League defeats the Ottoman fleet at Lepanto.", "Battle of Lepanto"),
 (1588, "The Spanish Armada is defeated.", "Spanish Armada"),
 (1599, "The Globe Theatre opens in London.", "Globe Theatre"),
 (1600, "The East India Company is chartered.", "East India Company"),
 (1603, "The Tokugawa shogunate begins in Japan.", "Tokugawa shogunate"),
 (1609, "Galileo turns a telescope on the night sky.", "Galileo Galilei"),
 (1616, "William Shakespeare dies.", "William Shakespeare"),
 (1618, "The Thirty Years' War begins.", "Thirty Years' War"),
 (1620, "The Mayflower sails to America.", "Mayflower"),
 (1632, "Work begins on the Taj Mahal.", "Taj Mahal"),
 (1642, "The English Civil War begins.", "English Civil War"),
 (1644, "The Qing dynasty takes Beijing.", "Qing dynasty"),
 (1648, "The Peace of Westphalia ends the Thirty Years' War.", "Peace of Westphalia"),
 (1666, "The Great Fire of London burns for four days.", "Great Fire of London"),
 (1683, "The Ottoman siege of Vienna is broken.", "Battle of Vienna"),
 (1687, "Newton publishes the Principia.", "Philosophiæ Naturalis Principia Mathematica"),
 (1707, "The Acts of Union create the Kingdom of Great Britain.", "Acts of Union 1707"),
 (1712, "Newcomen builds the first practical steam engine.", "Newcomen atmospheric engine"),
 (1721, "Peter the Great proclaims the Russian Empire.", "Russian Empire"),
 (1751, "The first volume of Diderot's Encyclopédie appears.", "Encyclopédie"),
 (1755, "An earthquake and tsunami destroy Lisbon.", "1755 Lisbon earthquake"),
 (1757, "The East India Company wins the Battle of Plassey.", "Battle of Plassey"),
 (1770, "James Cook charts the east coast of Australia.", "James Cook"),
 (1776, "The American colonies declare independence.", "United States Declaration of Independence"),
 (1783, "The Montgolfier brothers launch the first crewed balloon flight.", "Montgolfier brothers"),
 (1789, "The French Revolution begins.", "French Revolution"),
 (1796, "Edward Jenner tests the first smallpox vaccine.", "Edward Jenner"),
 (1804, "Haiti becomes independent after a slave revolution.", "Haitian Revolution"),
 (1815, "Napoleon is defeated at Waterloo.", "Battle of Waterloo"),
 (1825, "The first public steam railway opens in England.", "Stockton and Darlington Railway"),
 (1833, "Britain abolishes slavery across most of its empire.", "Slavery Abolition Act 1833"),
 (1839, "The First Opium War begins.", "First Opium War"),
 (1845, "The Great Famine begins in Ireland.", "Great Famine (Ireland)"),
 (1848, "Revolutions sweep across Europe.", "Revolutions of 1848"),
 (1857, "The Indian Rebellion breaks out against Company rule.", "Indian Rebellion of 1857"),
 (1859, "Darwin publishes On the Origin of Species.", "On the Origin of Species"),
 (1861, "The American Civil War begins.", "American Civil War"),
 (1868, "The Meiji Restoration begins Japan's modernisation.", "Meiji Restoration"),
 (1869, "The Suez Canal opens.", "Suez Canal"),
 (1871, "Germany is unified as an empire.", "Unification of Germany"),
 (1885, "The Berlin Conference carves up Africa among European powers.", "Berlin Conference"),
 (1896, "The first modern Olympic Games are held in Athens.", "1896 Summer Olympics"),
 (1903, "The Wright brothers make the first powered flight.", "Wright Flyer"),
 (1912, "The Titanic sinks on her maiden voyage.", "Titanic"),
 (1914, "The First World War begins.", "World War I"),
 (1917, "Revolution overthrows the Russian monarchy.", "Russian Revolution"),
 (1918, "The influenza pandemic spreads worldwide.", "Spanish flu"),
 (1928, "Alexander Fleming discovers penicillin.", "Penicillin"),
 (1929, "The Wall Street Crash begins the Great Depression.", "Wall Street crash of 1929"),
 (1939, "The Second World War begins.", "World War II"),
 (1945, "The United Nations is founded.", "United Nations"),
 (1947, "India becomes independent, and is partitioned.", "Partition of India"),
 (1949, "The People's Republic of China is proclaimed.", "China"),
 (1953, "Scientists describe the double-helix structure of DNA.", "Nucleic acid double helix"),
 (1957, "The Soviet Union launches Sputnik 1.", "Sputnik 1"),
 (1962, "The Cuban Missile Crisis brings the world to the brink.", "Cuban Missile Crisis"),
 (1969, "Apollo 11 lands on the Moon.", "Apollo 11"),
 (1975, "Saigon falls, ending the Vietnam War.", "Fall of Saigon"),
 (1986, "The Chernobyl nuclear disaster.", "Chernobyl disaster"),
 (1989, "The Berlin Wall falls.", "Fall of the Berlin Wall"),
 (1991, "The World Wide Web opens to the public.", "World Wide Web"),
 (1994, "Nelson Mandela is elected president of South Africa.", "1994 South African general election"),
 (2001, "The September 11 attacks strike the United States.", "September 11 attacks"),
 (2004, "The Indian Ocean tsunami kills over 200,000 people.", "2004 Indian Ocean earthquake and tsunami"),
 (2008, "A global financial crisis begins.", "2008 financial crisis"),
 (2011, "The Arab Spring spreads across the Middle East.", "Arab Spring"),
 (2020, "The COVID-19 pandemic spreads worldwide.", "COVID-19 pandemic"),
 (2022, "Russia launches a full-scale invasion of Ukraine.", "Russian invasion of Ukraine"),
]
